currency_converter_currency_converter_homepage:
    pattern:  /
    defaults: { _controller: CurrencyConverterCurrencyConverterBundle:Home:index }
    
currency_converter_currency_converter_about:
    pattern:  /about
    defaults: { _controller: CurrencyConverterCurrencyConverterBundle:Home:about }

currency_converter_currency_converter_contact:
    pattern:  /contact
    defaults: { _controller: CurrencyConverterCurrencyConverterBundle:Home:contact }
    requirements:
        _method:  GET|POST