<?php

namespace CurrencyConverter\CurrencyConverterBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
    public function getAllCountries($limit=null){
        
        $qb = $this->createQueryBuilder('c')
                   ->select('c');                  
                   
        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
                   
    }
    
}
